### ISSUE TITLE
ReadMe: We need to create a proper readme.txt for the wordpress repo

### ISSUE THREAD

**Issue by kjbenk** [kjbenk/get-notified#5]
@wpmonty would you want to handle this?

**Comment by wpmonty** [comment]
@kjbenk yes, I will handle it

**Comment by kjbenk** [comment]
@wpmonty I submitted the plugin and created a v1 readme.  Once the plugin gets downloads we can enhance it.

**Comment by wpmonty** [comment]
@kjbenk I've updated the readme and some internal info as well; PR submitted #10
